name: Feature request
description: Suggest an improvement or a new feature
labels: enhancement
body:
  - type: textarea
    id: feature
    attributes:
      label: What would you like to be added?
      description: |
        You are *more than welcome* to open issue requesting new features. Please remember, however, **one feature per issue**
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Why is this needed?
    validations:
      required: false
