# Note regarding credentials
#
# These credentials are for local use ONLY. These WILL NOT work in an online env! Thats why file storing
# online creds is empty.
url: http://127.0.0.1:8080,
login: crowdsec
password: crowdsec